apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-autocluster
        image: rabbitmq-autocluster:latest
        # `Never` as we are not using registry in our `minikube` setup
        imagePullPolicy: Never
        env:
          # For consupmption by rabbitmq-env.conf
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          # start.sh will store this value to a proper location in filesystem
          - name: ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: erlang.cookie
                key: erlang.cookie
        command:
          - "/start.sh"
